# Generated by Django 6.0.1 on 2026-01-15 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_id_a08e3c_idx",
        ),
        migrations.RemoveField(
            model_name="category",
            name="id",
        ),
        migrations.AddField(
            model_name="category",
            name="category_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_id", "slug"], name="products_pr_product_b82e8a_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="product",
            name="id",
        ),
    ]
